# name: saucectl cypress tests

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# env:
#   SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
#   SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
#   SAUCECTL_VERSION: 0.176.0
#   BUILD_PREFIX: true
#   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# jobs:
#   build-web-app:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20'
#       - name: Install Dependencies
#         run: npm install

#   test-web-app:
#     runs-on: ubuntu-latest
#     needs: build-web-app
#     steps:
#       - name: Checkout GitHub App Code
#         uses: actions/checkout@v4
#       - name: Install Dependencies
#         run: npm install
#       - name: Start Local Server
#         run: |
#           npm run dev &  # Start your local server in the background
#           for i in {1..30}; do
#             curl -sSf http://localhost:5173 && break
#             echo "Waiting for server to start..."
#             sleep 5
#           done
#       # - name: Download & Use Sauce Connect Tunnel  # manually downlaod
#       #   run: |
#       #     set -e
#       #     curl -L -s https://saucelabs.com/downloads/sauce-connect/5.1.0/sauce-connect-5.1.0_linux.x86_64.tar.gz | sudo tar -xz
#       #     # sc-5.1.0-linux/bin/sc -u $SAUCE_USERNAME -k $SAUCE_ACCESS_KEY -i proxy-tunnel-$GITHUB_RUN_ID &
#       #     sc run -u oauth-sujeetsahu294-e4685 -k *****7250 --region eu-central --tunnel-name oauth-sujeetsahu294-e4685_tunnel_name
#       #     sleep 20  # Wait for the Sauce Connect tunnel to establish
#       # - name: Install Saucect   #manual installation
#       #   run: |
#       #     curl -L -s https://github.com/saucelabs/saucectl/releases/download/v${SAUCECTL_VERSION}/saucectl_${SAUCECTL_VERSION}_linux_64-bit.tar.gz | sudo tar -xz -C /usr/bin/
#       - name: Saucectl RUN
#         uses: saucelabs/saucectl-run-action@v3
#         with:
#           config-file: .sauce/config.yml
#           tunnel-name: github-action-tunnel
#           # tunnel-name: oauth-sujeetsahu294-e4685_tunnel_name
#         env:
#           SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
#           SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



name: saucectl cypress tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
  SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
  SAUCECTL_VERSION: 0.176.0
  BUILD_PREFIX: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-web-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install

  test-web-app:
    runs-on: ubuntu-latest
    needs: build-web-app
    steps:
      - name: Checkout GitHub App Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      # - name: Start Local Server
      #   run: |
      #     npm run dev &  # Start your local server in the background
      #     for i in {1..30}; do
      #       curl -sSf http://localhost:5173 && break
      #       echo "Waiting for server to start..."
      #       sleep 5
      #     done
      - name: Install wait-on
        run: npm install wait-on  # This line is added
      - name: Start Local Server
        run: npm run dev &
      - name: Wait for Server to Start
        run: |
          node -e "const waitOn = require('wait-on'); waitOn({ resources: [{ host: 'localhost', port: 5173 }], timeout: 15000 }).catch(err => { console.error('Server failed to start:', err); process.exit(1); }); console.log('Server is ready!');"
      # - name: Set up Sauce Connect
      #   uses: saucelabs/sauce-connect-action@v2
      #   with:
      #     username: ${{ secrets.SAUCE_USERNAME }}
      #     accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
      #     region: eu-central-1
      #     tunnelName: ${{ github.repository }}-${{ github.run_id }}
      #     # sauce-options: |-
      #     #   --tmp-dir /path/to/custom/tmp/dir  # Replace with your desired path
      # - name: Saucectl RUN
      #   uses: saucelabs/saucectl-run-action@v3
      #   with:
      #     config-file: .sauce/config.yml
      #     tunnel-name: ${{ github.repository }}-${{ github.run_id }}
      #   env:
      #     SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
      #     SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
